# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-25 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recognitionimage',
            options={'ordering': ['-pk']},
        ),
    ]
